### ISSUE TITLE
Timestamp helper could be updated based on latest moment.js

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/core-hbs-helpers#11]
The `timestamp` helper in this repo was written during a transitional time for [Moment.js](http://momentjs.com/). It has a few quirks that could be corrected:

- It uses `Date.now()` when Moment will default to the current date/time.
- It uses `Date.parse()` instead of Moment's [improved and highly customizable parsing](http://momentjs.com/docs/#/parsing/).
- It uses an `isNaN` check instead of Moment's [stricter `isValid` method](http://momentjs.com/docs/#/parsing/is-valid/) (which could potentially be used to provide more helpful error messages via `isValidAt`).
- It lacks the ability to activate [UTC mode](http://momentjs.com/docs/#/parsing/utc/), which can come in very handy for timestamps that are formatted with timezone assumptions.
- It specifies a `defaultFormat`, [which is not really necessary](http://momentjs.com/docs/#/displaying/) (`.format()` will output just fine without any arguments).

**Comment by erikjung** [comment]
@tylersticka Would you like to take a stab at cleaning this up? I think you're more in tune with the intricacies of Moment. I actually _added_ the `Date.parse()` and `isNaN` to comply with this:

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
```
(https://github.com/moment/moment/issues/1407)

Perhaps this is a non-issue. Though, I was getting an exception when writing tests that pass in garbage strings.

**Comment by tylersticka** [comment]
> Perhaps this is a non-issue. Though, I was getting an exception when writing tests that pass in garbage strings.

[This portion of the documentation](http://momentjs.com/docs/#/parsing/string/) explains what Moment supports now and what it falls back to, as well as how to parse non-standard strings. It's pretty neat.

> Would you like to take a stab at cleaning this up?

Sure!
