### ISSUE TITLE
Should `defaultTo` accept multiple fallbacks?

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/core-hbs-helpers#20]
`{{defaultTo something fallback}}` is one of my favorite helpers. While writing up cloudfour/drizzle-builder#82, I wondered if it might make sense to accept one or more arguments, returning the first one that evaluates truthy?

Example:

```
{{defaultTo something somethingElse "okay, fine"}}
```

**Comment by erikjung** [comment]
I can't think of an argument against this behavior. 👍
