### ISSUE TITLE
Update readme to link to documentation

### ISSUE THREAD

**Issue by erikjung** [cloudfour/core-hbs-helpers#25]
This project would be a good fit for https://doxdox.org

We can just output to `README.md` as Markdown.

**Comment by erikjung** [comment]
This could be done via npm scripts:

```
"scripts" {
  "docs": "doxdox lib --format markdown --output README.md"
}
```

**Comment by spaceninja** [comment]
We have doxdox now, so I'm marking this closed.

**Comment by Paul-Hebert** [comment]
@spaceninja our doxdox looks great! That said, I don't see it linked anywhere from this repo (though maybe I'm blind). Should we add a link to the README or something?

**Comment by spaceninja** [comment]
There's a pink button on the readme — but agreed, the readme should be update. I'll reclaim this ticket for that effort.

**Comment by Paul-Hebert** [comment]
Ahh, yeah I see it now. Thanks!
