### ISSUE TITLE
Nit: LICENSE isn't Markdown

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/core-hbs-helpers#31]
[According to GitHub](http://choosealicense.com/licenses/mit/), the license info is "typically named LICENSE or LICENSE.txt." Not sure why ours has the `.md` extension. ¯\_(ツ)_/¯

**Comment by spaceninja** [comment]
Looks like .md is an acceptable extension for the standard license file: https://help.github.com/en/articles/licensing-a-repository

Agreed, there's no markdown in there, but it's not hurting anything either.
