### ISSUE TITLE
Loosen up `timestamp` regular expression

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/core-hbs-helpers#37]
> timestamp
> 
>    2016-05-16T18:12:09Z
> /path/to/repo/core-hbs-helpers/test/timestamp.spec.js:20
>   test.ok(template().match(iso8601).length > 0, 'Works');
>                                    ^
> TypeError: Cannot read property 'length' of null

`moment.js` introduced recent changes that cause one of our tests to fail. The suggested action to take is to loosen up the [regular expression used in the `timestamp` test](https://github.com/cloudfour/core-hbs-helpers/blob/master/test/timestamp.spec.js#L13).

**Comment by tylersticka** [comment]
You might also consider ditching the regex check in favor of Moment's validation: http://momentjs.com/docs/#/parsing/is-valid/

**Comment by tylersticka** [comment]
@erikjung Can this issue be closed?

**Comment by erikjung** [comment]
@tylersticka Yes, it can.
