### ISSUE TITLE
Comments are needed

### ISSUE THREAD

**Issue by erikjung** [cloudfour/core-hbs-helpers#5]
Per discussion in #1, we should include comments in order to document each helper.

Format:

```js
/**
 * This is a helper that helps something.
 *
 * @since v0.1.0
 * @param {String} str
 * @return {String}
 * @see (if applicable)
 * @example
 *
 *   {{toSlug "Some String"}} //=> "some-string"
 */
```

**Comment by erikjung** [comment]
This should probably wait until after #4 so that the examples don't become instantly dated.

**Comment by tylersticka** [comment]
@erikjung I agree.

**Comment by erikjung** [comment]
@tylersticka Also, feel free to ignore any of the ones you feel are related to #3.
