### ISSUE TITLE
NPM HBS Helpers unable to read README

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/core-hbs-helpers#51]
If you view [this package](https://www.npmjs.com/package/@cloudfour/hbs-helpers) on NPM, you'll notice it can't get to the README.

> Unable to find a readme for @cloudfour/hbs-helpers@0.9.0

We should figure out why. 🤔

**Comment by spaceninja** [comment]
@gerardo-rodriguez this seems to have resolved itself.
