### ISSUE TITLE
"randomIf" is a potentially confusing name

### ISSUE THREAD

**Issue by erikjung** [cloudfour/core-hbs-helpers#8]
The `{{randomIf}}` helper behavior is to render the `fn` or `inverse` block at random. IMO, the inclusion of "if" in the name implies that there is some kind of conditional logic.

Would a different name be clearer?

```hbs
{{#randomBool}}This{{else}}That{{/randomBool}}
```
```hbs
{{#trueOrFalse}}This{{else}}That{{/trueOrFalse}}
```
```hbs
{{#maybe}}This{{else}}That{{/maybe}}
```

**Comment by tylersticka** [comment]
I kinda like `maybe`.

**Comment by erikjung** [comment]
```hbs
{{#maybe}}
  I do too.
{{/maybe}}
```
